### ISSUE TITLE
HTTP 502 on IsaTab download

### ISSUE THREAD

**Issue by ebirn** [1001genomes/AraPheno#25]
Hi,

The download for IsaTab dataset is currently causing a 502 error.

I can reproduce the problem with these urls:
https://arapheno.1001genomes.org/rest/study/1/isatab/
https://arapheno.1001genomes.org/rest/study/2/isatab/

**Comment by timeu** [comment]
We are running a Debian Jessie based container on a CentOS 7 VM and for some reason the gunicorn workers crashes with some invalid op code (SIGILL) in umath.so when a request caused the Backend to run some numpy code. in the requirements file numpy and scipy didn't have their versions pinned. Pinning the version and re-creating the container fixed the problem.
