### ISSUE TITLE
New Features and Extensions

### ISSUE THREAD

**Issue by dominikgrimm** [1001genomes/AraPheno#34]
- [x] araPheno Dashboard with statistics
- [x] Restructure landing page: Move Submit Phenotypes to first row and second row (Public Studies, Public Phenotypes, REST API) and third row (Submit Feedback, Take a Tour, FAQ)
- [x] Link to copy/download citation for study/phenotype
- [x] Add publication to phenotype detail view
- [x] Add button to popup with citation for Original publication and AraPheno
- [x] Download section to download full data in bulks (e. g. by study, all the data at once, Matteo)
- [x] Add "Study" Button to Home View
- [x] Update "Study Table" and add date when study was added
- [x] Bulk update meta-information
- [x] submit -> back to study (call it "save")
- [x] Remove source from phenotype?
- [x] simple upload and curration (Ümit) 
- [x] Add link to github
- [x] Feedback box 
- [x] Update About Page
- [x] Added Twitter Account to Landing Page 
- [x] three rows on homepage: (1) submit phenotypes (2) public pheno, public studies, REST API (3) Take a tour, FAQ, submit feedback (+ create github issue)

**Comment by timeu** [comment]
Hi Dominik, 
thanks for getting it started. I was planing to work on it this week/weekend.
You can leave some of the issues that require more changes in the backend to me. I can finish them until next week when we have the meeting.

**Comment by dominikgrimm** [comment]
Hi Ümit,
sure no worries. I had some minutes free. I will continuously add issues or checkboxes for tasks that are not yet implemented. I started with the feedback box, but I am not sure if I have enough time today to finish it. 
Best wishes,
Dominik

**Comment by dominikgrimm** [comment]
Some Studies or Phenotypes do not have publications in the database. We should add the name of the investigator to the phenotype view for those phenotypes. Otherwise it is not clear from whom the phenotype is. You only see the author if you click on the cite button:
https://arapheno.1001genomes.org/phenotype/699/

**Comment by timeu** [comment]
@dominikgrimm  This is a study to which the publication has not been published yet. The author asked me to make it public because the journal requires it.
