### ISSUE TITLE
Retrieve RNASeq data via REST API using GeneID

### ISSUE THREAD

**Issue by nschan** [1001genomes/AraPheno#40]
Hi, 

currently it seems like the REST API cannot be used to pull RNASeq data using GeneIDs (e.g. AT3G18050), but using a different ID (for AT3G18050 that id is 31786), could you add an option to query using GeneIDs (or transcript IDs)?

Thanks
Niklas

**Comment by timeu** [comment]
@nschan : 
Added an additional endpoint. However the gene_id itself is not enough. You also need to add the study_id (because the same gene could be phenotyped in multiple studies). 
The swagger API documentation should have all details
