### ISSUE TITLE
add sentence how to cite phenotypes with DOIs on faq/cite

### ISSUE THREAD

**Issue by arthurkorte** [1001genomes/AraPheno#9]

**Comment by timeu** [comment]
How should we formulate it ? 
For excample the doi link at the phenotype/study detail page leads to this site: 
http://search.datacite.org/works/10.21958/study:3#

From there you can easily generate citations

**Comment by arthurkorte** [comment]
Sounds good

Am 15.08.2016 6:54 Nachm. schrieb "Ümit Seren" <notifications@github.com>:

**Comment by timeu** [comment]
We should add an information to the FAQ how to cite a phenotype and add a info on the detailed view
